services:
  - type: web
    name: feature-flag-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: /api/v1
      - key: JWT_EXPIRES_IN
        value: 86400
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: feature-flag-postgres
          property: connectionString
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false

databases:
  - name: feature-flag-postgres
    plan: free
    databaseName: feature_flag
    user: feature_flag_user
